### PR TITLE
Create obconf-qt_ko.ts

### PR DESCRIPTION
**Pull request by MarongHappy**
Korean translation

### CODE REVIEW

**Comment by stefonarch** [comment]
Thanks  but all translations should go over weblate:
https://github.com/lxqt/lxqt/wiki/Translation

**Comment by MarongHappy** [comment]
Unable to access 'obconf-qt' from Weblast.



2021년 9월 24일 (금) 오후 6:34, Standreas ***@***.***>님이 작성:

**Comment by MarongHappy** [comment]
I don't see 'obconf-qt', and I can't find it when I search for it.

2021년 9월 24일 (금) 오후 7:29, Jung Hee Lee ***@***.***>님이 작성:

**Comment by MarongHappy** [comment]
Can't select Korean from
https://translate.lxqt-project.org/projects/lxqt-configuration/obconf-qt/

2021년 9월 24일 (금) 오후 7:30, Jung Hee Lee ***@***.***>님이 작성:

**Comment by MarongHappy** [comment]
It would be appreciated if you could forward the translated file to another
authorized translator.

2021년 9월 24일 (금) 오후 7:31, Jung Hee Lee ***@***.***>님이 작성:

**Comment by stefonarch** [comment]
> It would be appreciated if you could forward the translated file to another authorized translator. 

No need, you just needed upgraded permissions in weblate - this is done now, so you can add/upload your translations and create new translation files where there are missing. Thanks!

**Pull request closed without merging**
